function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function escapeText(t){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
push=function(who,text){const th=document.getElementById('thread'),el=document.createElement('div');el.className='msg'+(who==='me'?' me':'');if(who==='mentor'){const av=document.createElement('div');av.className='av';av.innerHTML=mentorFace(30);el.appendChild(av);}const bubble=document.createElement('div');bubble.className='bub';bubble.textContent=text;el.appendChild(bubble);const time=document.createElement('span');time.className='time';time.textContent=nowLabel();el.appendChild(time);th.appendChild(el);th.scrollTop=th.scrollHeight;return el;};
const originalGo=go;
go=function(id){if(['s-result','s-chat','s-compass','s-map'].includes(id)&&!state.saju)id='s-birth';originalGo(id);document.querySelectorAll('.screen').forEach(el=>{el.inert=el.id!==id;el.setAttribute('aria-hidden',el.id!==id?'true':'false');});if(id==='s-chat')initChat();const heading=document.querySelector('#'+id+' h1, #'+id+' h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}document.querySelector('.header-link').textContent=state.saju?'내 정보 수정 ↗':'내 사주 읽기 ↗';};
const originalBuild=buildResult;
buildResult=function(){document.getElementById('thread').innerHTML='';delete document.getElementById('thread').dataset.init;originalBuild();document.getElementById('personal-context').textContent=state.topics.length?`오늘의 상담 주제 · ${state.topics.join(' · ')}`:'당신의 궁금한 이야기를 들려주세요.';persist();};
const originalInit=initChat;
initChat=function(){const fresh=!document.getElementById('thread').dataset.init;originalInit();if(fresh&&(state.topicNote||state.topics.length)){push('mentor',state.topicNote?`남겨주신 고민, “${state.topicNote}”도 함께 살펴볼게요. 아래 주제를 고르거나 이야기를 이어가 주세요.`:`오늘은 ${state.topics.join(', ')} 이야기가 궁금하시군요. 어떤 상황인지 조금 더 들려주세요.`);}};
function persist(){try{localStorage.setItem('dalbit-v2',JSON.stringify({name:state.name,birth:state.birth,time:state.time,unknownTime:state.unknownTime,gender:state.gender,cal:state.cal,topics:state.topics,topicNote:state.topicNote,records:state.records}));return true;}catch(e){return false;}}
const originalSave=saveRecord;
saveRecord=function(){originalSave();document.getElementById('rec-note').value='';document.getElementById('c-rec').textContent='0';document.getElementById('rec-conf').value=55;if(!persist())alert('브라우저 저장 공간을 사용할 수 없어 이번에는 기록을 저장하지 못했어요.');};
const originalStart=startRecord;
startRecord=function(){state.draft={choice:null,conf:55,note:''};document.querySelectorAll('#rec-picks .pick,.mood,.res').forEach(x=>x.classList.remove('sel'));document.getElementById('rec-note').value='';document.getElementById('rec-conf').value=55;originalStart();};
document.getElementById('in-date').min='1900-01-01';document.getElementById('in-date').max=localDate();
[['in-name','이름 또는 별명'],['in-date','양력 생년월일'],['in-time','태어난 시간'],['chat-in','상담 메시지'],['in-topic-note','궁금한 고민'],['rec-note','선택에 대한 메모'],['rec-conf','선택에 대한 확신'],['rec-after','선택 후 돌아보기']].forEach(([id,label])=>document.getElementById(id).setAttribute('aria-label',label));
try{const saved=JSON.parse(localStorage.getItem('dalbit-v2')||'null');if(saved&&/^\d{4}-\d{2}-\d{2}$/.test(saved.birth)){Object.assign(state,saved);state.records=(saved.records||[]).map(r=>({...r,d:new Date(r.d)})).filter(r=>!isNaN(r.d));document.getElementById('in-name').value=state.name;document.getElementById('in-date').value=state.birth;document.getElementById('in-time').value=state.time;document.getElementById('in-unknown').checked=state.unknownTime;document.getElementById('in-time').disabled=state.unknownTime;document.getElementById('in-topic-note').value=state.topicNote||'';document.querySelectorAll('.opt').forEach(el=>el.classList.toggle('sel',el.dataset.val===state[el.dataset.group]));document.querySelectorAll('#topic-chips .chip').forEach(el=>el.classList.toggle('sel',state.topics.includes(el.dataset.t)));buildResult();}else go('s-splash');}catch(e){go('s-splash');}
